language: perl
perl:
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"

install:
    #This should solve problem installing Perl's DB_File
    - "sudo apt-get install libdb-dev 2>&1 | tail"
    - "cpanm --notest HTML::TableExtract DBI Data::Stag DB_File"
    - "cpanm --notest DBD::mysql DBD::Pg DBD::SQLite"
    - "cpanm --notest Algorithm::Munkres Array::Compare Convert::Binary::C Error"
    - "cpanm --notest Graph SVG SVG::Graph"
    - "cpanm --notest XML::DOM::XPath XML::Parser XML::Parser::PerlSAX"
    - "cpanm --notest XML::SAX XML::SAX::Writer XML::Simple XML::Twig XML::Writer"
    - "perl ./Build.PL --accept"

script:
    - "./Build test"

# whitelist branches
branches:
  only:
    - travis

#TODO - send emails to bioperl-guts-l
notifications:
  email: false
