language: perl
perl:
#  - "5.16"
#  - "5.14"
#  - "5.12"
  - "5.10"

install:
    #This should solve problem installing Perl's DB_File
    - "sudo apt-get install libdb-dev 2>&1 | tail"
    - "cpanm --notest HTML::TableExtract DBI Data::Stag DB_File"
    - "cpanm --notest DBD::mysql DBD::pg DBD::SQLite"
    - "perl ./Build.PL --accept"

script:
    - "./Build test"

# whitelist branches
branches:
  only:
    - travis

#TODO - send emails to bioperl-guts-l
notifications:
  email: false
